/**
 * Seed data — realistic workers and reviews for Meghalaya.
 * Loaded once on first app launch, then persisted to AsyncStorage.
 */
import { Worker, Review } from '@/types';

export const MOCK_WORKERS: Worker[] = [
  {
    id: 'worker_001',
    fullName: 'Bah David Kharkongor',
    profilePhoto: null,
    profession: 'Electrician',
    customProfession: null,
    about: 'Experienced electrician with 8 years of residential and commercial wiring experience. I handle everything from simple repairs to full rewiring. Licensed and insured for your peace of mind.',
    yearsOfExperience: 8,
    languages: ['Khasi', 'English', 'Hindi'],
    gender: 'Male',
    serviceAreas: ['Shillong', 'Mawlai', 'Nongthymmai', 'Laitumkhrah'],
    district: 'East Khasi Hills',
    phone: '+91 94361 23456',
    whatsapp: '+91 94361 23456',
    price: '₹500 per visit',
    availability: 'Full-time',
    serviceType: 'Home Visit',
    rating: 4.8,
    reviewCount: 24,
    isVerified: true,
    isApproved: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_002',
    fullName: 'Kong Pynki Lyngdoh',
    profilePhoto: null,
    profession: 'House Maid',
    customProfession: null,
    about: 'Reliable and trustworthy house maid with 5 years of experience. Punctual, hardworking, and I treat your home with care. Available 6 days a week.',
    yearsOfExperience: 5,
    languages: ['Khasi', 'English'],
    gender: 'Female',
    serviceAreas: ['Laitumkhrah', 'Shillong', 'Nongthymmai'],
    district: 'East Khasi Hills',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    price: '₹8,000 per month',
    availability: 'Full-time',
    serviceType: 'Home Visit',
    rating: 4.9,
    reviewCount: 18,
    isVerified: true,
    isApproved: true,
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_003',
    fullName: 'Bah Stanley Marak',
    profilePhoto: null,
    profession: 'Tourist Driver',
    customProfession: null,
    about: 'Professional tourist driver with excellent knowledge of Meghalaya. Comfortable Innova available. I can take you to all the beautiful spots — Cherrapunji, Dawki, Mawlynnong, and beyond.',
    yearsOfExperience: 10,
    languages: ['Garo', 'English', 'Hindi'],
    gender: 'Male',
    serviceAreas: ['Tura', 'Shillong', 'All Districts'],
    district: 'West Garo Hills',
    phone: '+91 97742 55678',
    whatsapp: '+91 97742 55678',
    price: '₹2,500 per day',
    availability: 'Full-time',
    serviceType: 'Both',
    rating: 4.7,
    reviewCount: 31,
    isVerified: true,
    isApproved: true,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_004',
    fullName: 'Kong Riki Shullai',
    profilePhoto: null,
    profession: 'Babysitter',
    customProfession: null,
    about: 'Caring and experienced babysitter with a background in early childhood education. Your child\'s safety and happiness is my priority. First aid certified.',
    yearsOfExperience: 4,
    languages: ['Khasi', 'English', 'Bengali'],
    gender: 'Female',
    serviceAreas: ['Shillong', 'Mawlai'],
    district: 'East Khasi Hills',
    phone: '+91 70052 11234',
    whatsapp: '+91 70052 11234',
    price: '₹6,000 per month',
    availability: 'Part-time',
    serviceType: 'Home Visit',
    rating: 5.0,
    reviewCount: 9,
    isVerified: false,
    isApproved: true,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_005',
    fullName: 'Bah Nixon Suchiang',
    profilePhoto: null,
    profession: 'Plumber',
    customProfession: null,
    about: 'Expert plumber for all types of plumbing work — pipe repairs, bathroom fittings, water tank installation, drain unblocking, and more. Quick response time.',
    yearsOfExperience: 12,
    languages: ['Khasi', 'Hindi', 'English'],
    gender: 'Male',
    serviceAreas: ['Shillong', 'Nongpoh', 'Byrnihat'],
    district: 'East Khasi Hills',
    phone: '+91 94361 88901',
    whatsapp: '+91 94361 88901',
    price: '₹400 per hour',
    availability: 'Full-time',
    serviceType: 'Home Visit',
    rating: 4.6,
    reviewCount: 42,
    isVerified: true,
    isApproved: true,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_006',
    fullName: 'Kong Mebanshan Khongstia',
    profilePhoto: null,
    profession: 'Home Tutor',
    customProfession: null,
    about: 'Qualified teacher with B.Ed degree offering home tuition for Classes 1–12. Specializing in Mathematics, Science, and English. Board exam preparation available.',
    yearsOfExperience: 7,
    languages: ['Khasi', 'English', 'Hindi'],
    gender: 'Female',
    serviceAreas: ['Shillong', 'Laitumkhrah', 'Mawlai'],
    district: 'East Khasi Hills',
    phone: '+91 98632 45789',
    whatsapp: '+91 98632 45789',
    price: '₹500 per hour',
    availability: 'Part-time',
    serviceType: 'Home Visit',
    rating: 4.9,
    reviewCount: 15,
    isVerified: true,
    isApproved: true,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_007',
    fullName: 'Bah Rikynmaw Nongrum',
    profilePhoto: null,
    profession: 'Photographer',
    customProfession: null,
    about: 'Professional photographer specializing in weddings, events, and portraits. Shot over 200 weddings across Meghalaya. Drone photography available.',
    yearsOfExperience: 6,
    languages: ['Khasi', 'English'],
    gender: 'Male',
    serviceAreas: ['Shillong', 'All Districts'],
    district: 'East Khasi Hills',
    phone: '+91 70055 67890',
    whatsapp: '+91 70055 67890',
    price: '₹15,000 per event',
    availability: 'Weekends',
    serviceType: 'Both',
    rating: 4.8,
    reviewCount: 28,
    isVerified: true,
    isApproved: true,
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_008',
    fullName: 'Kong Aidalin Dkhar',
    profilePhoto: null,
    profession: 'Cook',
    customProfession: null,
    about: 'Experienced cook specializing in Khasi traditional food, Indian cuisine, and Continental dishes. Available for daily cooking, parties, and corporate events.',
    yearsOfExperience: 8,
    languages: ['Khasi', 'English', 'Hindi'],
    gender: 'Female',
    serviceAreas: ['Shillong', 'Mawlai', 'Nongthymmai'],
    district: 'East Khasi Hills',
    phone: '+91 94367 34567',
    whatsapp: '+91 94367 34567',
    price: '₹10,000 per month',
    availability: 'Full-time',
    serviceType: 'Home Visit',
    rating: 4.7,
    reviewCount: 19,
    isVerified: false,
    isApproved: true,
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_009',
    fullName: 'Bah Samuel Sangma',
    profilePhoto: null,
    profession: 'Carpenter',
    customProfession: null,
    about: 'Skilled carpenter with expertise in furniture making, door and window fitting, modular kitchens, and interior woodwork. Quality craftsmanship guaranteed.',
    yearsOfExperience: 15,
    languages: ['Garo', 'Hindi', 'English'],
    gender: 'Male',
    serviceAreas: ['Tura', 'Williamnagar', 'West Garo Hills'],
    district: 'West Garo Hills',
    phone: '+91 91012 23456',
    whatsapp: '+91 91012 23456',
    price: '₹600 per day',
    availability: 'Full-time',
    serviceType: 'Home Visit',
    rating: 4.5,
    reviewCount: 36,
    isVerified: true,
    isApproved: true,
    createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_010',
    fullName: 'Kong Batskhem Rynjah',
    profilePhoto: null,
    profession: 'Makeup Artist',
    customProfession: null,
    about: 'Professional makeup artist trained in Kolkata. Specializing in bridal makeup, party looks, and fashion shoots. Uses premium international brands.',
    yearsOfExperience: 5,
    languages: ['Khasi', 'English', 'Bengali'],
    gender: 'Female',
    serviceAreas: ['Shillong', 'Laitumkhrah'],
    district: 'East Khasi Hills',
    phone: '+91 98011 78901',
    whatsapp: '+91 98011 78901',
    price: '₹3,000 per session',
    availability: 'Weekends',
    serviceType: 'Home Visit',
    rating: 4.9,
    reviewCount: 22,
    isVerified: false,
    isApproved: true,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_011',
    fullName: 'Bah Fullmoon Pathaw',
    profilePhoto: null,
    profession: 'Yoga Instructor',
    customProfession: null,
    about: 'Certified yoga instructor trained in Rishikesh. Offering individual and group sessions for all levels. Specializing in Hatha, Vinyasa, and meditation.',
    yearsOfExperience: 4,
    languages: ['Khasi', 'English', 'Hindi'],
    gender: 'Male',
    serviceAreas: ['Shillong', 'Nongthymmai'],
    district: 'East Khasi Hills',
    phone: '+91 76090 12345',
    whatsapp: '+91 76090 12345',
    price: '₹2,000 per month',
    availability: 'Part-time',
    serviceType: 'Both',
    rating: 4.6,
    reviewCount: 11,
    isVerified: false,
    isApproved: true,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    userId: null,
  },
  {
    id: 'worker_012',
    fullName: 'Kong Eudaimonia Lyngdoh Tariang',
    profilePhoto: null,
    profession: 'Accountant',
    customProfession: null,
    about: 'Chartered Accountant with 9 years of experience in taxation, audit, GST filing, and financial planning for individuals and small businesses across Meghalaya.',
    yearsOfExperience: 9,
    languages: ['Khasi', 'English', 'Hindi'],
    gender: 'Female',
    serviceAreas: ['Shillong'],
    district: 'East Khasi Hills',
    phone: '+91 94362 01234',
    whatsapp: '+91 94362 01234',
    price: '₹1,500 per consultation',
    availability: 'Full-time',
    serviceType: 'Both',
    rating: 4.8,
    reviewCount: 14,
    isVerified: true,
    isApproved: true,
    createdAt: new Date(Date.now() - 75 * 86400000).toISOString(),
    userId: null,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'review_001',
    workerId: 'worker_001',
    userId: 'user_seed_01',
    userName: 'Rishaan Das',
    rating: 5,
    comment: 'David fixed our entire house wiring in one day. Very professional and clean work. Highly recommended!',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'review_002',
    workerId: 'worker_001',
    userId: 'user_seed_02',
    userName: 'Priya Sharma',
    rating: 5,
    comment: 'Excellent work! He came on time and did the job perfectly. Very fair pricing.',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'review_003',
    workerId: 'worker_002',
    userId: 'user_seed_03',
    userName: 'Amit Roy',
    rating: 5,
    comment: 'Kong Pynki is absolutely wonderful. She takes great care of our home and is very trustworthy.',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'review_004',
    workerId: 'worker_003',
    userId: 'user_seed_04',
    userName: 'Jake Wilson',
    rating: 5,
    comment: 'Stanley was an amazing guide and driver! He took us to beautiful places and knew everything about Meghalaya.',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'review_005',
    workerId: 'worker_007',
    userId: 'user_seed_05',
    userName: 'Maria Lyngdoh',
    rating: 5,
    comment: 'Rikynmaw captured our wedding beautifully. Every single photo is perfect. Worth every penny!',
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
];
